Rewrite prefixMatch to use a for loop instead of Array prototype
Calling `Array.prototype.slice` with the `windowStyles` object causes
an `Uncaught TypeError: undefined is not a function` in Web Views of
older versions of Android (KitKat). This rewrites it to use a for loop.